### ISSUE TITLE
webtorrent-cli not installing

### ISSUE THREAD

**Issue by aj-arts** [Bugswriter/notflix#46]
i typed npm install webtorrent-cli -g
code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/webtorrent/http-node.git
npm ERR! /bin/bash: /root/.bashrc: Permission denied
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-04T06_42_59_518Z-debug.log

**Comment by porcupinecoder** [comment]
maybe this 
https://wiki.archlinux.org/title/Node.js#Allow_user-wide_installations

**Comment by walkxcode** [comment]
The SSH host key for GitHub has probably changed on your system. Please refer to this issue: https://github.com/webtorrent/webtorrent/issues/2027 or [this StackOverflow post](https://stackoverflow.com/a/13364116).

**Comment by voidpunk** [comment]
@aj-arts what's your OS?

**Comment by aj-arts** [comment]
Pop os

**Comment by Huzitive** [comment]
none of the above solution works

**Comment by Napoleon-x** [comment]
> i typed npm install webtorrent-cli -g code 128 npm ERR! command failed npm ERR! command git ls-remote ssh://git@github.com/webtorrent/http-node.git npm ERR! /bin/bash: /root/.bashrc: Permission denied npm ERR! [git@github.com](mailto:git@github.com): Permission denied (publickey). npm ERR! fatal: Could not read from remote repository. npm ERR! npm ERR! Please make sure you have the correct access rights npm ERR! and the repository exists.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2022-01-04T06_42_59_518Z-debug.log

are you new to Linux lol?
`sudo npm install webtorrent-cli -g`

**Comment by aj-arts** [comment]
bruh it doesn't work it just give ssh key error and tells can't access remote respoitory

**Comment by walkxcode** [comment]
> The SSH host key for GitHub has probably changed on your system. Please refer to this issue: [webtorrent/webtorrent#2027](https://github.com/webtorrent/webtorrent/issues/2027) or [this StackOverflow post](https://stackoverflow.com/a/13364116).

Have you read the link I send you. It should fix the SSH key error.

**Comment by aj-arts** [comment]
I even talked with the sponsor of the web torrent cli and he updated it to 4.0.2 and it still didn't solve the issue
he told it is working for some people and not for others. I even sent him the log file and he told that he will get back to me.
so currently for it get fixed

**Comment by aj-arts** [comment]
I never liked node package manager

**Comment by choudhary-akash** [comment]
Try this out: [](https://programmerah.com/solve-npm-err-code-128-33978)

**Comment by aj-arts** [comment]
ok will try this and tell you if it works

**Comment by choudhary-akash** [comment]
The first command on that page had some whitespace issue. Try this - 

```
git config --global url."https://github".insteadOf git://github

npm cache clean --force
```

**Comment by aj-arts** [comment]
ok

**Comment by aj-arts** [comment]
Lucky you

**Comment by walkxcode** [comment]
Hey @aj-arts , just had this issue on my linux install. Here are some steps to get it working.

- Very simple, but stupid. Don't install it globally. Simply run `npm install webtorrent-cli`

**Comment by ritchielrez** [comment]
This issue should not be opened here, I suppose. This is a **webtorrent** problem, not really problem **notfix** not working with **webtorrent**.
